In [1]:
from main import load_data

from sklearn.preprocessing import StandardScaler
from sklearn.impute import KNNImputer

from feature_selection import feature_selection_mutual_info_percentile
from outlier_detection import isolation_forest_outliers

from imputation import transform_df

folder = 'data'
X_train_df, y_train_df, X_predict_df = load_data(
    f'{folder}/X_train.csv', f'{folder}/y_train.csv', f'{folder}/X_test.csv')

In [2]:
#scaling &imputation

#scaling
scaler = StandardScaler()
scaler.fit(X_train_df)
X_train_df = transform_df(X_train_df, scaler)

#imputation
imputer = KNNImputer(n_neighbors=5)
imputer.fit(X_train_df)
X_train_df = transform_df(X_train_df, imputer)
X_train_df

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x822,x823,x824,x825,x826,x827,x828,x829,x830,x831
id,,,,,,,,,,,,,,,,,,,,,
0,-0.454501,-0.277582,-0.258752,-0.594780,-0.947206,-0.762591,1.147777,1.328498,1.183985,0.241674,...,0.415889,-0.427311,0.186727,0.058296,-1.047246,-0.750852,-0.128316,-0.473584,-1.765196,-0.685711
1,1.096353,1.631038,1.512020,-0.725778,0.031459,-0.011890,0.031510,1.185358,-1.454004,1.450007,...,-0.024069,1.353798,-0.200763,0.505235,-0.564885,-0.016508,-1.660892,1.240674,-1.359074,1.744715
2,-0.429505,0.050628,-0.625516,2.478770,-1.598072,-0.743372,0.319211,-0.013864,0.051439,0.823582,...,0.270170,0.324765,-0.417111,-0.462618,1.559508,0.331558,0.447956,-1.778206,-0.118178,-0.421251
3,-2.789636,-2.271433,-2.895826,0.016018,-0.075987,0.205001,0.068309,0.011889,0.101136,0.106150,...,-0.063199,-3.270789,-2.677858,0.041304,-0.072837,-2.648091,0.025036,-1.629656,-0.133716,0.101111
4,-0.613470,1.477362,-0.050810,-0.819659,-0.462565,-0.437117,-0.321895,0.913327,0.425965,2.019385,...,0.027577,0.230289,-0.282981,-0.118779,-1.665794,0.402249,-0.086337,0.419916,0.652556,-0.549836
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1207,1.507131,1.694719,0.801043,1.390739,1.572848,-0.225535,1.316283,1.104084,1.572621,-0.117899,...,-1.656262,2.061861,1.223147,-0.046389,-1.003815,1.178599,1.341720,0.010967,0.078349,0.127486
1208,0.815937,0.776077,0.026581,-0.183796,-1.624192,1.048487,1.068836,-0.948801,0.663327,0.252889,...,-1.275534,0.669792,-0.112235,0.304639,1.721634,1.226384,0.794569,0.819765,-0.874744,0.630398
1209,-0.413059,-1.068055,0.338549,0.171753,-0.864583,0.470783,-0.839616,0.594186,0.441124,0.146917,...,0.202364,0.903648,0.103669,-1.084658,-1.204691,-0.441036,1.426531,1.590407,0.484348,0.332013
1210,-0.135422,-0.008615,-0.612926,0.041049,0.547817,-1.580144,0.380673,-1.392889,-0.384208,-1.744712,...,0.249907,-0.138345,0.219898,-0.666902,-0.236431,0.195731,0.023180,-0.224719,-0.098985,0.882540
1211,-0.105646,0.319246,-0.729563,0.008040,1.048301,0.425837,0.799211,0.826450,0.472691,0.701225,...,-1.260292,-0.148990,0.591430,0.962553,-0.732700,0.012098,-0.017421,0.214302,1.236627,0.372822

In [ ]:
#remove outliers
X_train_df, y_train_df = isolation_forest_outliers(X_train_df, y_train_df, 0.1)

In [3]:
#feature selection
X_train_df, feature_selector = feature_selection_mutual_info_percentile(X_train_df, y_train_df)

c:\Users\domil\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1183: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

,x23,x27,x29,x69,x79,x87,x95,x115,x132,x133,...,x726,x734,x742,x745,x748,x759,x766,x769,x817,x818
id,,,,,,,,,,,,,,,,,,,,,
0,0.564054,0.162694,-0.651499,-0.498593,0.535994,0.408726,1.298240,1.165688,0.309316,-0.242720,...,-0.186629,0.627227,-0.368048,0.058584,1.059394,-0.268241,0.238071,0.291456,0.860234,1.596139
1,-0.130639,1.060528,0.599327,1.435782,-1.307368,1.460194,0.690965,-0.490523,-2.240820,0.892194,...,2.180760,0.422948,3.693261,0.797758,0.274575,1.695422,2.075849,-1.211102,-0.005933,1.470353
2,-0.008616,-0.378954,0.238014,-0.376605,0.523771,0.274540,0.913335,-0.452960,0.926172,0.425399,...,-1.117271,0.967933,-0.492389,-0.089778,-0.068092,-0.702646,0.379094,0.297055,0.291410,-0.276152
3,-1.780960,-3.236043,-2.683094,-3.846107,3.412562,-3.267531,0.001225,1.109370,3.132345,-2.927806,...,-2.473381,-1.879192,-0.897638,-1.470309,-2.021328,-3.311378,-1.967153,-1.670508,-1.918397,0.050638
4,-0.272044,-0.156025,2.225660,0.071527,0.069908,-0.122499,-0.743809,0.195010,0.350737,0.273856,...,1.054005,-1.051596,-0.283890,-0.055581,-0.335106,-0.062177,-0.141994,-0.674901,-0.516613,-0.196052
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1207,0.945179,1.477478,1.280500,1.758549,-1.465028,0.460817,1.223559,-0.479157,-0.680855,0.700920,...,0.411976,0.136584,0.551094,2.058196,0.557210,0.892897,0.464218,-0.263215,-0.335502,0.505469
1208,-0.780537,0.456224,0.977621,0.729286,-0.870639,0.729798,0.064202,-0.152594,-0.387212,-0.162289,...,1.476954,-0.780485,-0.213882,-0.422722,0.026675,0.290506,-0.846455,0.134119,-0.828284,0.307793
1209,0.804913,-0.145569,-0.334645,0.226127,0.427684,-0.088173,0.967656,-0.412465,-0.330361,0.416114,...,0.161098,0.893488,2.812776,1.286585,0.385492,-0.290345,1.745478,0.484019,0.340787,-0.743850
1210,-0.065484,0.044769,0.604876,-0.079255,0.550858,-0.191070,-0.657541,-0.066990,0.210784,-1.210307,...,-0.436377,-0.081549,-0.532652,0.105704,0.163551,-0.719469,0.963234,0.269989,0.718341,-1.248156
1211,0.026740,-0.195312,-0.226111,-0.208406,0.282349,-0.882253,0.652805,-0.757971,0.517212,-0.000454,...,-0.441756,0.744934,-0.378018,0.465222,-0.203021,-0.514415,0.709732,0.179190,0.126287,1.053209